TextileERPClient/Controllers/BaseController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TextileERPClient.Models;

namespace TextileERPClient.Controllers
{
    public class BaseController : Controller
    {
        private readonly ILogger logger;
        private readonly IConfiguration configuration;
        private readonly Keys keys;
        public BaseController(ILogger<BaseController> logger, IConfiguration configuration, IOptions<Keys> options)
        {
            keys = options.Value;
            this.logger = logger;
            this.configuration = configuration;
        }

        private string _userauth;
        protected string UserAuth
        {
            get
            {
                _userauth = HttpContext.Session.GetString("AuthUser");
                return _userauth;
            }
        }
        [HttpPost]
        public IActionResult UserAuthentication(User user)
        {
            if (user != null && (user.UserName == "admin" && user.Password == "admin@KK"))
            {
                HttpContext.Session.SetString("AuthUser", "KK Siripuram");
                return RedirectToAction("Dashboard", "Home");
            }
            else
            {
                TempData["ErrorMessage"] = "Invalid Credentials.";
                return RedirectToAction("Login", "Home");
            }
        }
        public string UserSession()
        {
            string auth = HttpContext.Session.GetString("AuthUser");
            if (!string.IsNullOrEmpty(auth))
            {
                HttpContext.Session.SetString("AuthUser", auth);
                return auth;
            }
            else
            {
                return null;
            }

        }
    }
}

TextileERPClient/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TextileERPClient.Models;

namespace TextileERPClient.Controllers
{
    public class HomeController : BaseController
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger, IConfiguration configuration, IOptions<Keys> options) : base(logger, configuration, options)
        {
            this._logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Login()
        {

            return View();
        }
        public IActionResult ContactUs()
        {
            return View();
        }
        public IActionResult DashBoard()
        {
            if (UserAuth != null)
            {
                return View();
            }
            else
            {
                return View("SessionOut");
            }
        }
        public IActionResult AboutUs()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login","Home");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TextileERPClient/ViewComponents/CountryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Net.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using TextileERPClient.Models;

namespace TextileERPClient.ViewComponents
{
    public class CountryViewComponent : ViewComponent
    {
        private readonly Keys keys;
        public CountryViewComponent(IOptions<Keys> options)
        {
            this.keys = options.Value;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<SelectListItem> listItems = new List<SelectListItem>();
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress =new Uri(keys.ServiceURL);
                string res = await client.GetStringAsync("api/master/ddcountries");
                if(res != null && res.Length > 0)
                {
                    listItems = JsonConvert.DeserializeObject<List<SelectListItem>>(res);
                }
                
                Console.WriteLine(res);
                return View(listItems);
            }
        }
    }
}

TextileERPClient/Views/Home/AboutUs.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

TextileERPClient/Views/Home/ContactUs.cshtml
@await Component.InvokeAsync("Country")

TextileERPClient/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center" id="welcome_div">
    <h1 class="display-4"><strong> WELCOME TO SARTY TEXTILES </strong> </h1>
    <p> Experience the best designing cloths and look perfect every day<p>
</div>

TextileERPClient/Views/Home/Login.cshtml
@model User

@{ 
    string msg = TempData["ErrorMessage"] == null ? "" : TempData["ErrorMessage"].ToString();
   
}

<input type="hidden" id="swal_msg"/>
<div class="container ">
    <div class="align-items-lg-end form-div">
        <form asp-action="UserAuthentication" asp-controller="Base" method="post">
            <div class="row m-3">
                <div class="col-md-3 ">
                    <label> <strong>User Name:</strong></label>
                </div>
                <div class="col-md-4">
                    <input type="text" required asp-for="@Model.UserName" class="form-control" autocomplete="off"/>
                </div>
            </div>
            <div class="row m-3">
                <div class="col-md-3">
                    <label style="text-align:right;"> <strong>Password:</strong></label>
                </div>
                <div class="col-md-4">
                    <input type="password" required asp-for="@Model.Password" class="form-control" />
                </div>
            </div>
            <div class="row m-3">
                <div class="col-md-3">&nbsp;</div>
                <div class="col-md-6">
                    <button type="submit" class="btn btn-success"> Login </button> &nbsp; <button type="reset" class="btn btn-primary">Clear</button>
                </div>
            </div>

        </form>
    </div>
</div>